{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Author: ML Tlachac, WPI\n",
    "#For StudentSADD, 2021\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.feature_selection import SelectKBest, chi2\n",
    "from sklearn import preprocessing\n",
    "from scipy import stats\n",
    "import collections\n",
    "import operator\n",
    "import argparse\n",
    "import random\n",
    "from sklearn.model_selection import cross_validate\n",
    "from sklearn.model_selection import cross_val_predict\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn.metrics import recall_score\n",
    "from sklearn import metrics\n",
    "from statistics import mean \n",
    "from sklearn.naive_bayes import GaussianNB\n",
    "from sklearn.utils import resample\n",
    "from sklearn import preprocessing\n",
    "from sklearn import utils\n",
    "from sklearn.datasets import load_digits\n",
    "from sklearn import svm\n",
    "import xgboost as xgb\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "import random\n",
    "from sklearn.decomposition import PCA, KernelPCA, NMF"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(110, 2271)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>phq9</th>\n",
       "      <th>q9</th>\n",
       "      <th>F0final_sma_f0v_duration</th>\n",
       "      <th>audspec_lengthL1norm_sma_quartile1</th>\n",
       "      <th>audspec_lengthL1norm_sma_quartile2</th>\n",
       "      <th>audspec_lengthL1norm_sma_quartile3</th>\n",
       "      <th>audspec_lengthL1norm_sma_iqr1-2</th>\n",
       "      <th>audspec_lengthL1norm_sma_iqr2-3</th>\n",
       "      <th>audspec_lengthL1norm_sma_iqr1-3</th>\n",
       "      <th>...</th>\n",
       "      <th>logHNR_sma_de_risetime</th>\n",
       "      <th>F0final_sma_f0v_nnz</th>\n",
       "      <th>F0final_sma_f0v_meanSegLen</th>\n",
       "      <th>F0final_sma_f0v_maxSegLen</th>\n",
       "      <th>F0final_sma_f0v_minSegLen</th>\n",
       "      <th>F0final_sma_f0v_segLenStddev</th>\n",
       "      <th>F0final_sma_f0p_meanSegLen</th>\n",
       "      <th>F0final_sma_f0p_maxSegLen</th>\n",
       "      <th>F0final_sma_f0p_minSegLen</th>\n",
       "      <th>F0final_sma_f0p_segLenStddev</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8181</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>29.72</td>\n",
       "      <td>0.053588</td>\n",
       "      <td>0.121533</td>\n",
       "      <td>0.279239</td>\n",
       "      <td>0.067945</td>\n",
       "      <td>0.157706</td>\n",
       "      <td>0.225651</td>\n",
       "      <td>...</td>\n",
       "      <td>0.428375</td>\n",
       "      <td>0.399394</td>\n",
       "      <td>0.237500</td>\n",
       "      <td>1.20</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.192370</td>\n",
       "      <td>0.368723</td>\n",
       "      <td>3.18</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.611432</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>8170</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>19.12</td>\n",
       "      <td>0.014378</td>\n",
       "      <td>0.023862</td>\n",
       "      <td>0.076276</td>\n",
       "      <td>0.009483</td>\n",
       "      <td>0.052414</td>\n",
       "      <td>0.061898</td>\n",
       "      <td>...</td>\n",
       "      <td>0.448418</td>\n",
       "      <td>0.288180</td>\n",
       "      <td>0.167742</td>\n",
       "      <td>0.57</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.124323</td>\n",
       "      <td>0.428387</td>\n",
       "      <td>4.53</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.821184</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>4041</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>29.60</td>\n",
       "      <td>0.054657</td>\n",
       "      <td>0.080013</td>\n",
       "      <td>0.177709</td>\n",
       "      <td>0.025356</td>\n",
       "      <td>0.097696</td>\n",
       "      <td>0.123052</td>\n",
       "      <td>...</td>\n",
       "      <td>0.444540</td>\n",
       "      <td>0.318919</td>\n",
       "      <td>0.238947</td>\n",
       "      <td>0.79</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.188216</td>\n",
       "      <td>0.519474</td>\n",
       "      <td>3.48</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.737228</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8650</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>29.82</td>\n",
       "      <td>0.140065</td>\n",
       "      <td>0.247997</td>\n",
       "      <td>0.375071</td>\n",
       "      <td>0.107933</td>\n",
       "      <td>0.127074</td>\n",
       "      <td>0.235007</td>\n",
       "      <td>...</td>\n",
       "      <td>0.432584</td>\n",
       "      <td>0.525486</td>\n",
       "      <td>0.210704</td>\n",
       "      <td>0.58</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.149160</td>\n",
       "      <td>0.189014</td>\n",
       "      <td>1.94</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.278452</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4782</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>29.65</td>\n",
       "      <td>0.041752</td>\n",
       "      <td>0.075815</td>\n",
       "      <td>0.195711</td>\n",
       "      <td>0.034062</td>\n",
       "      <td>0.119896</td>\n",
       "      <td>0.153958</td>\n",
       "      <td>...</td>\n",
       "      <td>0.457752</td>\n",
       "      <td>0.326813</td>\n",
       "      <td>0.210455</td>\n",
       "      <td>0.77</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.154375</td>\n",
       "      <td>0.453023</td>\n",
       "      <td>1.90</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.491564</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows Ã— 2271 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     id  phq9  q9  F0final_sma_f0v_duration  \\\n",
       "0  8181     0   0                     29.72   \n",
       "1  8170     0   0                     19.12   \n",
       "2  4041     1   0                     29.60   \n",
       "3  8650     1   0                     29.82   \n",
       "4  4782     1   0                     29.65   \n",
       "\n",
       "   audspec_lengthL1norm_sma_quartile1  audspec_lengthL1norm_sma_quartile2  \\\n",
       "0                            0.053588                            0.121533   \n",
       "1                            0.014378                            0.023862   \n",
       "2                            0.054657                            0.080013   \n",
       "3                            0.140065                            0.247997   \n",
       "4                            0.041752                            0.075815   \n",
       "\n",
       "   audspec_lengthL1norm_sma_quartile3  audspec_lengthL1norm_sma_iqr1-2  \\\n",
       "0                            0.279239                         0.067945   \n",
       "1                            0.076276                         0.009483   \n",
       "2                            0.177709                         0.025356   \n",
       "3                            0.375071                         0.107933   \n",
       "4                            0.195711                         0.034062   \n",
       "\n",
       "   audspec_lengthL1norm_sma_iqr2-3  audspec_lengthL1norm_sma_iqr1-3  ...  \\\n",
       "0                         0.157706                         0.225651  ...   \n",
       "1                         0.052414                         0.061898  ...   \n",
       "2                         0.097696                         0.123052  ...   \n",
       "3                         0.127074                         0.235007  ...   \n",
       "4                         0.119896                         0.153958  ...   \n",
       "\n",
       "   logHNR_sma_de_risetime  F0final_sma_f0v_nnz  F0final_sma_f0v_meanSegLen  \\\n",
       "0                0.428375             0.399394                    0.237500   \n",
       "1                0.448418             0.288180                    0.167742   \n",
       "2                0.444540             0.318919                    0.238947   \n",
       "3                0.432584             0.525486                    0.210704   \n",
       "4                0.457752             0.326813                    0.210455   \n",
       "\n",
       "   F0final_sma_f0v_maxSegLen  F0final_sma_f0v_minSegLen  \\\n",
       "0                       1.20                       0.02   \n",
       "1                       0.57                       0.03   \n",
       "2                       0.79                       0.03   \n",
       "3                       0.58                       0.02   \n",
       "4                       0.77                       0.03   \n",
       "\n",
       "   F0final_sma_f0v_segLenStddev  F0final_sma_f0p_meanSegLen  \\\n",
       "0                      0.192370                    0.368723   \n",
       "1                      0.124323                    0.428387   \n",
       "2                      0.188216                    0.519474   \n",
       "3                      0.149160                    0.189014   \n",
       "4                      0.154375                    0.453023   \n",
       "\n",
       "   F0final_sma_f0p_maxSegLen  F0final_sma_f0p_minSegLen  \\\n",
       "0                       3.18                       0.02   \n",
       "1                       4.53                       0.02   \n",
       "2                       3.48                       0.02   \n",
       "3                       1.94                       0.02   \n",
       "4                       1.90                       0.02   \n",
       "\n",
       "   F0final_sma_f0p_segLenStddev  \n",
       "0                      0.611432  \n",
       "1                      0.821184  \n",
       "2                      0.737228  \n",
       "3                      0.278452  \n",
       "4                      0.491564  \n",
       "\n",
       "[5 rows x 2271 columns]"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#data = pd.read_csv(\"unscriptedML.csv\")\n",
    "#unscriptedML.csv\n",
    "#aPromptTextFeatures.csv\n",
    "#tPromptTextFeatures.csv\n",
    "print(data.shape)\n",
    "\n",
    "#binary labels\n",
    "d10 = []\n",
    "s1 = []\n",
    "for i in range(0, data.shape[0]):\n",
    "    if int(data.phq9[i]) >= 10:\n",
    "        d10.append(1)\n",
    "    else:\n",
    "        d10.append(0)\n",
    "    if int(data.q9[i]) >= 1:\n",
    "        s1.append(1)\n",
    "    else:\n",
    "        s1.append(0)\n",
    "data[\"phq9\"] = d10\n",
    "data[\"q9\"] = s1\n",
    "data.head()\n",
    "\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>phq9</th>\n",
       "      <th>q9</th>\n",
       "      <th>F0final_sma_f0v_duration</th>\n",
       "      <th>audspec_lengthL1norm_sma_quartile1</th>\n",
       "      <th>audspec_lengthL1norm_sma_quartile2</th>\n",
       "      <th>audspec_lengthL1norm_sma_quartile3</th>\n",
       "      <th>audspec_lengthL1norm_sma_iqr1-2</th>\n",
       "      <th>audspec_lengthL1norm_sma_iqr2-3</th>\n",
       "      <th>audspec_lengthL1norm_sma_iqr1-3</th>\n",
       "      <th>...</th>\n",
       "      <th>logHNR_sma_de_risetime</th>\n",
       "      <th>F0final_sma_f0v_nnz</th>\n",
       "      <th>F0final_sma_f0v_meanSegLen</th>\n",
       "      <th>F0final_sma_f0v_maxSegLen</th>\n",
       "      <th>F0final_sma_f0v_minSegLen</th>\n",
       "      <th>F0final_sma_f0v_segLenStddev</th>\n",
       "      <th>F0final_sma_f0p_meanSegLen</th>\n",
       "      <th>F0final_sma_f0p_maxSegLen</th>\n",
       "      <th>F0final_sma_f0p_minSegLen</th>\n",
       "      <th>F0final_sma_f0p_segLenStddev</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8181</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>29.72</td>\n",
       "      <td>0.053588</td>\n",
       "      <td>0.121533</td>\n",
       "      <td>0.279239</td>\n",
       "      <td>0.067945</td>\n",
       "      <td>0.157706</td>\n",
       "      <td>0.225651</td>\n",
       "      <td>...</td>\n",
       "      <td>0.428375</td>\n",
       "      <td>0.399394</td>\n",
       "      <td>0.237500</td>\n",
       "      <td>1.20</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.192370</td>\n",
       "      <td>0.368723</td>\n",
       "      <td>3.18</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.611432</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>8170</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>19.12</td>\n",
       "      <td>0.014378</td>\n",
       "      <td>0.023862</td>\n",
       "      <td>0.076276</td>\n",
       "      <td>0.009483</td>\n",
       "      <td>0.052414</td>\n",
       "      <td>0.061898</td>\n",
       "      <td>...</td>\n",
       "      <td>0.448418</td>\n",
       "      <td>0.288180</td>\n",
       "      <td>0.167742</td>\n",
       "      <td>0.57</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.124323</td>\n",
       "      <td>0.428387</td>\n",
       "      <td>4.53</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.821184</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>4041</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>29.60</td>\n",
       "      <td>0.054657</td>\n",
       "      <td>0.080013</td>\n",
       "      <td>0.177709</td>\n",
       "      <td>0.025356</td>\n",
       "      <td>0.097696</td>\n",
       "      <td>0.123052</td>\n",
       "      <td>...</td>\n",
       "      <td>0.444540</td>\n",
       "      <td>0.318919</td>\n",
       "      <td>0.238947</td>\n",
       "      <td>0.79</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.188216</td>\n",
       "      <td>0.519474</td>\n",
       "      <td>3.48</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.737228</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8650</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>29.82</td>\n",
       "      <td>0.140065</td>\n",
       "      <td>0.247997</td>\n",
       "      <td>0.375071</td>\n",
       "      <td>0.107933</td>\n",
       "      <td>0.127074</td>\n",
       "      <td>0.235007</td>\n",
       "      <td>...</td>\n",
       "      <td>0.432584</td>\n",
       "      <td>0.525486</td>\n",
       "      <td>0.210704</td>\n",
       "      <td>0.58</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.149160</td>\n",
       "      <td>0.189014</td>\n",
       "      <td>1.94</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.278452</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4782</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>29.65</td>\n",
       "      <td>0.041752</td>\n",
       "      <td>0.075815</td>\n",
       "      <td>0.195711</td>\n",
       "      <td>0.034062</td>\n",
       "      <td>0.119896</td>\n",
       "      <td>0.153958</td>\n",
       "      <td>...</td>\n",
       "      <td>0.457752</td>\n",
       "      <td>0.326813</td>\n",
       "      <td>0.210455</td>\n",
       "      <td>0.77</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.154375</td>\n",
       "      <td>0.453023</td>\n",
       "      <td>1.90</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.491564</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows Ã— 2271 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     id  phq9  q9  F0final_sma_f0v_duration  \\\n",
       "0  8181     0   0                     29.72   \n",
       "1  8170     0   0                     19.12   \n",
       "2  4041     1   0                     29.60   \n",
       "3  8650     1   0                     29.82   \n",
       "4  4782     1   0                     29.65   \n",
       "\n",
       "   audspec_lengthL1norm_sma_quartile1  audspec_lengthL1norm_sma_quartile2  \\\n",
       "0                            0.053588                            0.121533   \n",
       "1                            0.014378                            0.023862   \n",
       "2                            0.054657                            0.080013   \n",
       "3                            0.140065                            0.247997   \n",
       "4                            0.041752                            0.075815   \n",
       "\n",
       "   audspec_lengthL1norm_sma_quartile3  audspec_lengthL1norm_sma_iqr1-2  \\\n",
       "0                            0.279239                         0.067945   \n",
       "1                            0.076276                         0.009483   \n",
       "2                            0.177709                         0.025356   \n",
       "3                            0.375071                         0.107933   \n",
       "4                            0.195711                         0.034062   \n",
       "\n",
       "   audspec_lengthL1norm_sma_iqr2-3  audspec_lengthL1norm_sma_iqr1-3  ...  \\\n",
       "0                         0.157706                         0.225651  ...   \n",
       "1                         0.052414                         0.061898  ...   \n",
       "2                         0.097696                         0.123052  ...   \n",
       "3                         0.127074                         0.235007  ...   \n",
       "4                         0.119896                         0.153958  ...   \n",
       "\n",
       "   logHNR_sma_de_risetime  F0final_sma_f0v_nnz  F0final_sma_f0v_meanSegLen  \\\n",
       "0                0.428375             0.399394                    0.237500   \n",
       "1                0.448418             0.288180                    0.167742   \n",
       "2                0.444540             0.318919                    0.238947   \n",
       "3                0.432584             0.525486                    0.210704   \n",
       "4                0.457752             0.326813                    0.210455   \n",
       "\n",
       "   F0final_sma_f0v_maxSegLen  F0final_sma_f0v_minSegLen  \\\n",
       "0                       1.20                       0.02   \n",
       "1                       0.57                       0.03   \n",
       "2                       0.79                       0.03   \n",
       "3                       0.58                       0.02   \n",
       "4                       0.77                       0.03   \n",
       "\n",
       "   F0final_sma_f0v_segLenStddev  F0final_sma_f0p_meanSegLen  \\\n",
       "0                      0.192370                    0.368723   \n",
       "1                      0.124323                    0.428387   \n",
       "2                      0.188216                    0.519474   \n",
       "3                      0.149160                    0.189014   \n",
       "4                      0.154375                    0.453023   \n",
       "\n",
       "   F0final_sma_f0p_maxSegLen  F0final_sma_f0p_minSegLen  \\\n",
       "0                       3.18                       0.02   \n",
       "1                       4.53                       0.02   \n",
       "2                       3.48                       0.02   \n",
       "3                       1.94                       0.02   \n",
       "4                       1.90                       0.02   \n",
       "\n",
       "   F0final_sma_f0p_segLenStddev  \n",
       "0                      0.611432  \n",
       "1                      0.821184  \n",
       "2                      0.737228  \n",
       "3                      0.278452  \n",
       "4                      0.491564  \n",
       "\n",
       "[5 rows x 2271 columns]"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#only use this cell for multimodal models or to load scripted audio\n",
    "\n",
    "audio = pd.read_csv(\"ScriptedML.csv\")\n",
    "#audio = audio.drop(columns = [\"phq9\",\"q9\"])\n",
    "\n",
    "#data = data.merge(audio, on = \"id\", how = \"inner\")\n",
    "#print(data.shape)\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "testids = [1607712777, 292, 2613, 1610640355, 1607494599, 1607040811, 1608492986, 6390, 396, 1607734901, 1607350992, 1608992344, 1609903202, 74, 7159, 4698, 7547, 4441, 1607097951, 8479, 8170, 4707, 7516, 1609174124, 1608853150, 8516, 1611424664, 2843, 1607040596, 1953, 1607772081, 1608564004, 2627, 1607217921, 1607118643, 1607314413, 1609887404, 1608335387, 4098, 1607046006, 1608242917, 8918, 1607131299, 9754, 1607262842, 1607273026, 2478, 1607536408, 1607291545, 1608707232, 1609941585, 1608200497, 1610630377, 7711, 1607810287, 9934, 1608850448, 4041, 1609166629, 1608168856, 1607572897, 6831, 1608586814, 1608588581, 2837, 8180, 1608631410, 1607051003, 3830, 4879, 1608920128, 1607019351, 8181, 3473, 1608335906, 1607738757, 1608770486, 7564, 1607495239, 1609983150, 1607397061, 1607696074, 103, 2222]\n",
    "trainids = [4769, 1607928177, 1607269923, 7755, 4598, 1607807806, 1608741452, 3323, 1610110670, 1607133044, 9745, 1607291670, 5245, 4442, 319, 1607133218, 1607010270, 1608587203, 1609256130, 1608582258, 5028, 1609771771, 5229, 3517, 1608595561, 1608048050, 1607410780, 528, 1607134906, 3102, 1607555727, 1609887167, 3985, 7256, 3523, 1607289708, 1609890222, 850, 1608917024, 5047, 1608061691, 4782, 1608062276, 1056, 1611517276, 1607636681, 1607891972, 5571, 1609052616, 1607927243, 2525, 4353, 1610818662, 8640, 1607559849, 6706, 1608624428, 1607968838, 1608672132, 552, 1608537399, 1610381937, 1608607986, 381, 1608589576, 3920, 1608059746, 1609027319, 1607357022, 1607691623, 1609899907, 1608470962, 8791, 1610380419, 3064, 1609473849, 1607712704, 1609887249, 1609888813, 1608588103, 1244, 7279, 1607339125, 1607712682, 8472, 1269, 1607045076, 1607365865, 1846, 191, 1811, 1608702785, 1609049435, 5330, 1607257348, 1609890530, 3278, 1608586899, 1607939718, 2430, 1609893292, 60, 1607270186, 6336, 8650, 1608495626, 1608586953, 2121, 1607295286, 896, 1609889389, 1607560754, 6548, 6580, 1607440988, 1609111416, 1607807159, 8663, 1607129044, 6658, 1607799213, 3933, 1608596696, 1608663032, 1610791060, 1607135820, 1607413039, 1607659758, 1608487726, 4859, 1609142183, 1607276888, 7452, 1607368510, 1607266081, 2623, 1608416516, 2128, 3227, 5881, 6510, 1609166843, 7569, 1607712793, 1608850996, 3273, 1607939838, 9986, 3302, 1607206195, 1609082904, 1607510222, 7612, 1607022963, 1607051040, 1607719324, 1608849324, 1607642639, 1607104225, 705, 1608506424, 1608188073, 8018, 8085, 4755, 1611704179, 1607193886, 7007, 3041, 4001, 1552, 1716, 1608053349, 1608572299, 1608051417, 1607712784, 836, 1607929944, 1607795480, 1608200317, 415, 3662, 1610109929, 2496, 8550, 6868, 1608587385, 1608591490, 7370, 4549, 7505, 1879, 1876, 1608003341]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(33, 2271)\n",
      "(65, 2271)\n"
     ]
    }
   ],
   "source": [
    "#train/test split\n",
    "testdata = data[data['id'].isin(testids)]\n",
    "print(testdata.shape)\n",
    "traindata = data[data['id'].isin(trainids)]\n",
    "print(traindata.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(33, 2268)\n",
      "(65, 2268)\n"
     ]
    }
   ],
   "source": [
    "#limit to features\n",
    "testContent = testdata[testdata.columns[3:]]\n",
    "print(testContent.shape)\n",
    "trainContent = traindata[traindata.columns[3:]]\n",
    "print(trainContent.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(65, 2268)\n",
      "(33, 2268)\n"
     ]
    }
   ],
   "source": [
    "#NEED TO SCALE BEFORE FEATURE SELECTION/REDUCATION\n",
    "\n",
    "min_max_scaler = preprocessing.MinMaxScaler()  \n",
    "np_scaled = min_max_scaler.fit_transform(trainContent)\n",
    "featureSubset = pd.DataFrame(np_scaled)\n",
    "np_scaled2 =  min_max_scaler.transform(testContent)\n",
    "testSubset = pd.DataFrame(np_scaled2)\n",
    "print(featureSubset.shape)\n",
    "print(testSubset.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PCA\n",
      "0\n",
      "          0\n",
      "3 -5.109159\n",
      "4 -4.892737\n",
      "5 -4.688972\n",
      "6 -6.075516\n",
      "7 -7.351165\n",
      "          0\n",
      "0 -2.982864\n",
      "1 -5.335472\n",
      "2 -4.950867\n",
      "3 -7.992718\n",
      "4 -5.569734\n",
      "PCA\n",
      "1\n",
      "          0         1\n",
      "3 -5.109159 -3.753238\n",
      "4 -4.892737 -3.448511\n",
      "5 -4.688972 -3.375943\n",
      "6 -6.075516 -2.976051\n",
      "7 -7.351165 -2.834562\n",
      "          0         1\n",
      "0 -2.982864 -4.205019\n",
      "1 -5.335472 -3.001037\n",
      "2 -4.950867 -3.807158\n",
      "3 -7.992718 -3.006346\n",
      "4 -5.569734 -2.900340\n",
      "PCA\n",
      "2\n",
      "          0         1         2\n",
      "3 -5.109159 -3.753239 -0.629525\n",
      "4 -4.892737 -3.448514 -0.795109\n",
      "5 -4.688972 -3.375953 -1.617050\n",
      "6 -6.075516 -2.976054 -1.381249\n",
      "7 -7.351165 -2.834555 -1.086337\n",
      "          0         1         2\n",
      "0 -2.982864 -4.205019 -0.336421\n",
      "1 -5.335472 -3.001038 -0.990356\n",
      "2 -4.950867 -3.807156  0.827379\n",
      "3 -7.992718 -3.006343  0.669584\n",
      "4 -5.569734 -2.900341  0.042430\n",
      "PCA\n",
      "3\n",
      "          0         1         2         3\n",
      "3 -5.109159 -3.753237 -0.629523 -1.257811\n",
      "4 -4.892737 -3.448513 -0.795109 -1.908024\n",
      "5 -4.688972 -3.375947 -1.616985 -1.954438\n",
      "6 -6.075516 -2.976053 -1.381261 -1.778222\n",
      "7 -7.351165 -2.834558 -1.086351 -1.547900\n",
      "          0         1         2         3\n",
      "0 -2.982864 -4.205019 -0.336423 -1.591484\n",
      "1 -5.335472 -3.001038 -0.990351 -0.830007\n",
      "2 -4.950867 -3.807158  0.827360 -0.093250\n",
      "3 -7.992718 -3.006345  0.669566  0.653652\n",
      "4 -5.569734 -2.900342  0.042405 -0.607266\n",
      "PCA\n",
      "4\n",
      "          0         1         2         3         4\n",
      "3 -5.109159 -3.753237 -0.629546 -1.257674  1.064862\n",
      "4 -4.892737 -3.448514 -0.795110 -1.908043 -0.051990\n",
      "5 -4.688972 -3.375949 -1.617000 -1.954589  1.119408\n",
      "6 -6.075516 -2.976052 -1.381245 -1.778204 -0.470981\n",
      "7 -7.351165 -2.834556 -1.086328 -1.547891  1.407882\n",
      "          0         1         2         3         4\n",
      "0 -2.982864 -4.205019 -0.336423 -1.591516  0.142075\n",
      "1 -5.335472 -3.001038 -0.990351 -0.829993 -0.044784\n",
      "2 -4.950867 -3.807158  0.827368 -0.093278 -0.165036\n",
      "3 -7.992718 -3.006344  0.669579  0.653630  2.362196\n",
      "4 -5.569734 -2.900341  0.042428 -0.607274 -0.615963\n",
      "PCA\n",
      "5\n",
      "          0         1         2         3         4         5\n",
      "3 -5.109159 -3.753238 -0.629537 -1.257763  1.064943 -0.767649\n",
      "4 -4.892737 -3.448513 -0.795110 -1.908022 -0.051984 -0.121475\n",
      "5 -4.688972 -3.375949 -1.617004 -1.954540  1.120250  1.112601\n",
      "6 -6.075516 -2.976052 -1.381240 -1.778268 -0.471180 -0.949648\n",
      "7 -7.351165 -2.834557 -1.086333 -1.547946  1.407372 -1.686655\n",
      "          0         1         2         3         4         5\n",
      "0 -2.982864 -4.205018 -0.336422 -1.591468  0.142399  1.736949\n",
      "1 -5.335472 -3.001038 -0.990349 -0.830020 -0.044801  0.150329\n",
      "2 -4.950867 -3.807157  0.827365 -0.093221 -0.164686  0.054441\n",
      "3 -7.992718 -3.006344  0.669580  0.653596  2.362165 -0.765423\n",
      "4 -5.569734 -2.900341  0.042430 -0.607321 -0.616446 -1.034656\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PCA\n",
      "6\n",
      "          0         1         2         3         4         5         6\n",
      "3 -5.109160 -3.753418 -0.627476 -1.265819  1.080956 -0.780611 -0.279333\n",
      "4 -4.892736 -3.448597 -0.794262 -1.910242 -0.047559 -0.115949  0.001008\n",
      "5 -4.688977 -3.375816 -1.616734 -1.955374  1.122923  1.114845 -0.201538\n",
      "6 -6.075517 -2.976108 -1.380626 -1.779378 -0.467646 -0.940848 -0.190986\n",
      "7 -7.351159 -2.834506 -1.087668 -1.543497  1.398095 -1.682913  0.529369\n",
      "          0         1         2         3         4         5         6\n",
      "0 -2.982865 -4.205088 -0.335819 -1.593683  0.148445  1.733987  1.650309\n",
      "1 -5.335474 -3.000910 -0.990976 -0.828780 -0.046733  0.147160  1.466012\n",
      "2 -4.950870 -3.807077  0.826997 -0.092742 -0.166769  0.055731  1.036304\n",
      "3 -7.992720 -3.006320  0.669137  0.654085  2.357568 -0.770269  0.843321\n",
      "4 -5.569738 -2.900285  0.042125 -0.605500 -0.621138 -1.031175 -0.188276\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "0\n",
      "          0\n",
      "3  0.000000\n",
      "4  0.166812\n",
      "5  0.044242\n",
      "6  0.095108\n",
      "7  0.135974\n",
      "          0\n",
      "0  0.259511\n",
      "1  0.864327\n",
      "2  0.959019\n",
      "3  0.185150\n",
      "4  0.097188\n",
      "Chi\n",
      "1\n",
      "          0    1\n",
      "3  0.000000  0.0\n",
      "4  0.166812  0.0\n",
      "5  0.044242  0.0\n",
      "6  0.095108  0.0\n",
      "7  0.135974  0.0\n",
      "          0         1\n",
      "0  0.259511  0.000000\n",
      "1  0.864327  0.090909\n",
      "2  0.959019  0.090909\n",
      "3  0.185150  0.000000\n",
      "4  0.097188  0.000000\n",
      "Chi\n",
      "2\n",
      "          0         1    2\n",
      "3  0.000000  0.041218  0.0\n",
      "4  0.166812  0.798180  0.0\n",
      "5  0.044242  0.373133  0.0\n",
      "6  0.095108  0.321030  0.0\n",
      "7  0.135974  0.018703  0.0\n",
      "          0         1         2\n",
      "0  0.259511  0.787507  0.000000\n",
      "1  0.864327  0.186580  0.090909\n",
      "2  0.959019  0.018580  0.090909\n",
      "3  0.185150  0.046298  0.000000\n",
      "4  0.097188  0.013907  0.000000\n",
      "Chi\n",
      "3\n",
      "          0         1         2    3\n",
      "3  0.000000  0.003184  0.041218  0.0\n",
      "4  0.166812  0.003585  0.798180  0.0\n",
      "5  0.044242  0.044193  0.373133  0.0\n",
      "6  0.095108  0.005054  0.321030  0.0\n",
      "7  0.135974  0.007377  0.018703  0.0\n",
      "          0         1         2         3\n",
      "0  0.259511  0.011406  0.787507  0.000000\n",
      "1  0.864327  0.009702  0.186580  0.090909\n",
      "2  0.959019  0.006352  0.018580  0.090909\n",
      "3  0.185150  0.033667  0.046298  0.000000\n",
      "4  0.097188  0.005662  0.013907  0.000000\n",
      "Chi\n",
      "4\n",
      "          0         1         2         3    4\n",
      "3  0.015276  0.000000  0.003184  0.041218  0.0\n",
      "4  0.015276  0.166812  0.003585  0.798180  0.0\n",
      "5  0.032902  0.044242  0.044193  0.373133  0.0\n",
      "6  0.016451  0.095108  0.005054  0.321030  0.0\n",
      "7  0.003525  0.135974  0.007377  0.018703  0.0\n",
      "          0         1         2         3         4\n",
      "0  0.022327  0.259511  0.011406  0.787507  0.000000\n",
      "1  0.008226  0.864327  0.009702  0.186580  0.090909\n",
      "2  0.050529  0.959019  0.006352  0.018580  0.090909\n",
      "3  0.009401  0.185150  0.033667  0.046298  0.000000\n",
      "4  0.021152  0.097188  0.005662  0.013907  0.000000\n",
      "Chi\n",
      "5\n",
      "          0         1         2         3         4    5\n",
      "3  0.001200  0.015276  0.000000  0.003184  0.041218  0.0\n",
      "4  0.001752  0.015276  0.166812  0.003585  0.798180  0.0\n",
      "5  0.001148  0.032902  0.044242  0.044193  0.373133  0.0\n",
      "6  0.001695  0.016451  0.095108  0.005054  0.321030  0.0\n",
      "7  0.003004  0.003525  0.135974  0.007377  0.018703  0.0\n",
      "          0         1         2         3         4         5\n",
      "0  0.001734  0.022327  0.259511  0.011406  0.787507  0.000000\n",
      "1  0.001864  0.008226  0.864327  0.009702  0.186580  0.090909\n",
      "2  0.000210  0.050529  0.959019  0.006352  0.018580  0.090909\n",
      "3 -0.002071  0.009401  0.185150  0.033667  0.046298  0.000000\n",
      "4  0.001064  0.021152  0.097188  0.005662  0.013907  0.000000\n",
      "Chi\n",
      "6\n",
      "          0         1         2         3         4         5    6\n",
      "3  0.001200  0.007079  0.015276  0.000000  0.003184  0.041218  0.0\n",
      "4  0.001752  0.007628  0.015276  0.166812  0.003585  0.798180  0.0\n",
      "5  0.001148  0.001404  0.032902  0.044242  0.044193  0.373133  0.0\n",
      "6  0.001695  0.000936  0.016451  0.095108  0.005054  0.321030  0.0\n",
      "7  0.003004  0.001061  0.003525  0.135974  0.007377  0.018703  0.0\n",
      "          0         1         2         3         4         5         6\n",
      "0  0.001734  0.002957  0.022327  0.259511  0.011406  0.787507  0.000000\n",
      "1  0.001864  0.002798  0.008226  0.864327  0.009702  0.186580  0.090909\n",
      "2  0.000210  0.000160  0.050529  0.959019  0.006352  0.018580  0.090909\n",
      "3 -0.002071 -0.002247  0.009401  0.185150  0.033667  0.046298  0.000000\n",
      "4  0.001064  0.000357  0.021152  0.097188  0.005662  0.013907  0.000000\n",
      "PCA\n",
      "0\n",
      "          0\n",
      "0 -1.638014\n",
      "1 -3.684931\n",
      "2 -2.195911\n",
      "3 -5.109159\n",
      "4 -4.892737\n",
      "          0\n",
      "0 -2.982864\n",
      "1 -5.335472\n",
      "2 -4.950867\n",
      "3 -7.992718\n",
      "4 -5.569734\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PCA\n",
      "1\n",
      "          0         1\n",
      "0 -1.638014 -4.616355\n",
      "1 -3.684931 -3.835945\n",
      "2 -2.195910 -4.736406\n",
      "3 -5.109159 -3.753240\n",
      "4 -4.892737 -3.448511\n",
      "          0         1\n",
      "0 -2.982864 -4.205017\n",
      "1 -5.335472 -3.001036\n",
      "2 -4.950867 -3.807158\n",
      "3 -7.992718 -3.006344\n",
      "4 -5.569734 -2.900338\n",
      "PCA\n",
      "2\n",
      "          0         1         2\n",
      "0 -1.638014 -4.616363 -0.756582\n",
      "1 -3.684931 -3.835946 -0.603257\n",
      "2 -2.195910 -4.736407 -0.354258\n",
      "3 -5.109159 -3.753237 -0.629548\n",
      "4 -4.892737 -3.448514 -0.795119\n",
      "          0         1         2\n",
      "0 -2.982864 -4.205018 -0.336427\n",
      "1 -5.335472 -3.001038 -0.990351\n",
      "2 -4.950867 -3.807157  0.827376\n",
      "3 -7.992718 -3.006345  0.669607\n",
      "4 -5.569734 -2.900341  0.042410\n",
      "PCA\n",
      "3\n",
      "          0         1         2         3\n",
      "0 -1.638014 -4.616363 -0.756569 -1.650797\n",
      "1 -3.684931 -3.835947 -0.603254 -1.222803\n",
      "2 -2.195910 -4.736407 -0.354281 -1.457748\n",
      "3 -5.109159 -3.753238 -0.629536 -1.257892\n",
      "4 -4.892737 -3.448513 -0.795110 -1.907928\n",
      "          0         1         2         3\n",
      "0 -2.982864 -4.205018 -0.336418 -1.591430\n",
      "1 -5.335472 -3.001038 -0.990356 -0.829946\n",
      "2 -4.950867 -3.807157  0.827370 -0.093296\n",
      "3 -7.992718 -3.006345  0.669572  0.653659\n",
      "4 -5.569734 -2.900340  0.042425 -0.607073\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PCA\n",
      "4\n",
      "          0         1         2         3         4\n",
      "0 -1.638014 -4.616362 -0.756567 -1.650663 -0.857954\n",
      "1 -3.684931 -3.835946 -0.603255 -1.222783 -0.313206\n",
      "2 -2.195910 -4.736405 -0.354268 -1.457717 -0.426527\n",
      "3 -5.109159 -3.753238 -0.629538 -1.257772  1.064485\n",
      "4 -4.892737 -3.448514 -0.795111 -1.907968 -0.051194\n",
      "          0         1         2         3         4\n",
      "0 -2.982864 -4.205018 -0.336420 -1.591451  0.142285\n",
      "1 -5.335472 -3.001038 -0.990349 -0.830033 -0.044989\n",
      "2 -4.950867 -3.807156  0.827367 -0.093194 -0.164597\n",
      "3 -7.992718 -3.006344  0.669580  0.653670  2.362742\n",
      "4 -5.569734 -2.900341  0.042432 -0.607279 -0.615951\n",
      "PCA\n",
      "5\n",
      "          0         1         2         3         4         5\n",
      "0 -1.638014 -4.616363 -0.756568 -1.650775 -0.859053  1.681494\n",
      "1 -3.684931 -3.835946 -0.603266 -1.222822 -0.312670  1.124117\n",
      "2 -2.195910 -4.736406 -0.354269 -1.457805 -0.426722  1.076396\n",
      "3 -5.109159 -3.753238 -0.629535 -1.257766  1.065003 -0.767825\n",
      "4 -4.892737 -3.448514 -0.795109 -1.907970 -0.052083 -0.121237\n",
      "          0         1         2         3         4         5\n",
      "0 -2.982864 -4.205018 -0.336428 -1.591490  0.142524  1.737440\n",
      "1 -5.335472 -3.001038 -0.990347 -0.830020 -0.044878  0.150288\n",
      "2 -4.950867 -3.807157  0.827361 -0.093250 -0.164656  0.054560\n",
      "3 -7.992718 -3.006345  0.669580  0.653633  2.362404 -0.765160\n",
      "4 -5.569734 -2.900340  0.042428 -0.607316 -0.616306 -1.034395\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PCA\n",
      "6\n",
      "          0         1         2         3         4         5         6\n",
      "0 -1.638009 -4.616448 -0.756667 -1.650467 -0.861637  1.676011  1.024679\n",
      "1 -3.684928 -3.835842 -0.603264 -1.222190 -0.313753  1.124520  1.231913\n",
      "2 -2.195917 -4.736113 -0.353599 -1.459397 -0.425010  1.081469  1.727553\n",
      "3 -5.109159 -3.753155 -0.629502 -1.259788  1.059353 -0.768372 -0.174726\n",
      "4 -4.892743 -3.448443 -0.795020 -1.906632 -0.047160 -0.123951 -0.005863\n",
      "          0         1         2         3         4         5         6\n",
      "0 -2.982860 -4.204934 -0.336391 -1.590793  0.138669  1.737956  1.670091\n",
      "1 -5.335470 -3.001152 -0.990709 -0.829030 -0.050502  0.150294  1.447944\n",
      "2 -4.950865 -3.807011  0.827570 -0.093882 -0.162823  0.053112  1.040403\n",
      "3 -7.992722 -3.006329  0.669716  0.653302  2.364517 -0.763794  0.838743\n",
      "4 -5.569733 -2.900371  0.042490 -0.606205 -0.612934 -1.038886 -0.198771\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "0\n",
      "          0\n",
      "0  0.028778\n",
      "1  0.000396\n",
      "2  0.004523\n",
      "3  0.069242\n",
      "4  0.007092\n",
      "          0\n",
      "0  0.001156\n",
      "1  0.000012\n",
      "2  0.002766\n",
      "3  0.002994\n",
      "4  0.000160\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "1\n",
      "          0         1\n",
      "0  0.000109  0.028778\n",
      "1  0.045062  0.000396\n",
      "2  0.161728  0.004523\n",
      "3  0.000000  0.069242\n",
      "4  0.000000  0.007092\n",
      "          0         1\n",
      "0  0.000265  0.001156\n",
      "1  0.001138  0.000012\n",
      "2  0.241975  0.002766\n",
      "3  0.206173  0.002994\n",
      "4  0.002432  0.000160\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "2\n",
      "          0         1         2\n",
      "0  0.000109  0.013581  0.028778\n",
      "1  0.045062  0.000636  0.000396\n",
      "2  0.161728  0.003485  0.004523\n",
      "3  0.000000  0.067157  0.069242\n",
      "4  0.000000  0.006639  0.007092\n",
      "          0         1         2\n",
      "0  0.000265  0.001485  0.001156\n",
      "1  0.001138  0.000036  0.000012\n",
      "2  0.241975  0.001303  0.002766\n",
      "3  0.206173  0.001200  0.002994\n",
      "4  0.002432  0.000046  0.000160\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "3\n",
      "          0         1         2         3\n",
      "0  0.000109  0.013581  0.028778  0.000313\n",
      "1  0.045062  0.000636  0.000396  0.011446\n",
      "2  0.161728  0.003485  0.004523  0.003612\n",
      "3  0.000000  0.067157  0.069242  0.000471\n",
      "4  0.000000  0.006639  0.007092  0.000473\n",
      "          0         1         2         3\n",
      "0  0.000265  0.001485  0.001156  0.000315\n",
      "1  0.001138  0.000036  0.000012  0.002781\n",
      "2  0.241975  0.001303  0.002766  0.000318\n",
      "3  0.206173  0.001200  0.002994  0.001655\n",
      "4  0.002432  0.000046  0.000160  0.004005\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "4\n",
      "          0         1         2         3         4\n",
      "0  0.000109  0.013581  0.028778  0.004396  0.000313\n",
      "1  0.045062  0.000636  0.000396  0.000094  0.011446\n",
      "2  0.161728  0.003485  0.004523  0.002252  0.003612\n",
      "3  0.000000  0.067157  0.069242  0.004344  0.000471\n",
      "4  0.000000  0.006639  0.007092  0.003088  0.000473\n",
      "          0         1         2         3         4\n",
      "0  0.000265  0.001485  0.001156  0.000323  0.000315\n",
      "1  0.001138  0.000036  0.000012  0.000002  0.002781\n",
      "2  0.241975  0.001303  0.002766  0.000054  0.000318\n",
      "3  0.206173  0.001200  0.002994  0.000023  0.001655\n",
      "4  0.002432  0.000046  0.000160  0.000011  0.004005\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "5\n",
      "          0         1         2         3         4         5\n",
      "0  0.000109  0.013581  0.028778  0.004367  0.004396  0.000313\n",
      "1  0.045062  0.000636  0.000396  0.000091  0.000094  0.011446\n",
      "2  0.161728  0.003485  0.004523  0.002252  0.002252  0.003612\n",
      "3  0.000000  0.067157  0.069242  0.004354  0.004344  0.000471\n",
      "4  0.000000  0.006639  0.007092  0.003090  0.003088  0.000473\n",
      "          0         1         2         3         4         5\n",
      "0  0.000265  0.001485  0.001156  0.000319  0.000323  0.000315\n",
      "1  0.001138  0.000036  0.000012  0.000002  0.000002  0.002781\n",
      "2  0.241975  0.001303  0.002766  0.000052  0.000054  0.000318\n",
      "3  0.206173  0.001200  0.002994  0.000023  0.000023  0.001655\n",
      "4  0.002432  0.000046  0.000160  0.000011  0.000011  0.004005\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chi\n",
      "6\n",
      "          0         1         2         3         4         5         6\n",
      "0  0.000109  0.013581  0.014760  0.028778  0.004367  0.004396  0.000313\n",
      "1  0.045062  0.000636  0.000959  0.000396  0.000091  0.000094  0.011446\n",
      "2  0.161728  0.003485  0.001923  0.004523  0.002252  0.002252  0.003612\n",
      "3  0.000000  0.067157  0.009005  0.069242  0.004354  0.004344  0.000471\n",
      "4  0.000000  0.006639  0.002201  0.007092  0.003090  0.003088  0.000473\n",
      "          0         1         2         3         4         5         6\n",
      "0  0.000265  0.001485  0.000915  0.001156  0.000319  0.000323  0.000315\n",
      "1  0.001138  0.000036  0.000022  0.000012  0.000002  0.000002  0.002781\n",
      "2  0.241975  0.001303  0.000920  0.002766  0.000052  0.000054  0.000318\n",
      "3  0.206173  0.001200  0.000015  0.002994  0.000023  0.000023  0.001655\n",
      "4  0.002432  0.000046  0.000941  0.000160  0.000011  0.000011  0.004005\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n",
      "C:\\Users\\mltla\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:162: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    }
   ],
   "source": [
    "labels = [\"phq9\", \"q9\"]\n",
    "featureEs = [\"PCA\", \"Chi\"]\n",
    "modelTypelist = [\"NB\", \"XG2\", \"XG3\", \"XG4\", \"LR1\", \"LR2\", \"SVC1\", \"SVC2\", \"SVC3\", \"SVC4\", \"kNN1\", \"kNN3\", \"kNN5\", \"kNN7\", \"kNN9\", \"RF2g\", \"RF2e\", \"RF3g\", \"RF3e\", \"RF4g\", \"RF4e\"]\n",
    "\n",
    "for label in labels:\n",
    "    \n",
    "    target = list(traindata[label])\n",
    "    \n",
    "    for featureE in featureEs:\n",
    "    \n",
    "        featureDF = []\n",
    "        testDFs = []\n",
    "\n",
    "        #chi-squared feature selection\n",
    "        if featureE == \"Chi\":\n",
    "            nFeatureList = list(np.arange(1,8,1)) #iterate through number of features to select\n",
    "\n",
    "            for numberOfFeatures in nFeatureList:\n",
    "                chisetup = SelectKBest(chi2, k=numberOfFeatures)\n",
    "                chisetup = chisetup.fit(featureSubset, target) #fit model with training data\n",
    "                featureSubset2 = chisetup.transform(featureSubset) #apply to training data\n",
    "                featureSubset2=pd.DataFrame(featureSubset2).assign(target = target) #add target\n",
    "                featureDF.append(featureSubset2) #save to list for later use\n",
    "                testSubset2 = chisetup.transform(testSubset) #apply to testing data\n",
    "                testDFs.append(pd.DataFrame(testSubset2)) #create dataframe and save to list for later use\n",
    "\n",
    "        #principal component analysis\n",
    "        elif featureE == \"PCA\":\n",
    "            nFeatureList = list(np.arange(1,8,1)) #iterate through number of principal components to store\n",
    "            for numberOfFeatures in nFeatureList:\n",
    "                pca = PCA(n_components=numberOfFeatures)\n",
    "                pca = pca.fit(featureSubset) #fit model with traning data\n",
    "                X_pca = pca.transform(featureSubset) #apply to training data\n",
    "                pcaDF = pd.DataFrame(X_pca) #create dataframe of results\n",
    "                pcaDF = pcaDF.assign(target = target) #add target\n",
    "                featureDF.append(pcaDF) #save to list for later use\n",
    "                testSubset2 = pca.transform(testSubset) #apply to testing data\n",
    "                testDFs.append(pd.DataFrame(testSubset2)) #create dataframe and save to list for later use\n",
    "                \n",
    "                \n",
    "        #create lists to populate\n",
    "        flist = [] \n",
    "        mlist = []\n",
    "        llist = []\n",
    "        featureList = []\n",
    "        f1List = []\n",
    "        accuracyList = []\n",
    "        truePosList = []\n",
    "        trueNegList = []\n",
    "        falsePosList = []\n",
    "        falseNegList = []\n",
    "        predictions = []\n",
    "        rseed = []\n",
    "        \n",
    "        for f in range(0, len(featureDF)):\n",
    "            print(featureE)\n",
    "            print(f)\n",
    "            \n",
    "            train_phq9 = featureDF[f] #select correct dataframe for training\n",
    "            X_test = testDFs[f] #select correct dataframe for testing\n",
    "            \n",
    "            # upsampling \n",
    "            #Count 1s and 0s\n",
    "            ones = len(train_phq9.loc[train_phq9['target'] == 1])\n",
    "            zeros = len(train_phq9.loc[train_phq9['target'] == 0])\n",
    "            if ones >= zeros:\n",
    "                majority = 1\n",
    "                minority = 0\n",
    "            else:\n",
    "                majority = 0\n",
    "                minority = 1\n",
    "\n",
    "            \n",
    "            # Upsample TrainingSet \n",
    "            train_majority = train_phq9[train_phq9.target==majority]\n",
    "            train_minority = train_phq9[train_phq9.target==minority]\n",
    "\n",
    "            # Upsample minority class\n",
    "            train_minority_upsampled = resample(train_minority, \n",
    "                                             replace=True,     # sample with replacement\n",
    "                                             n_samples=len(train_majority),    # to match majority class\n",
    "                                             random_state=42) # reproducible results\n",
    "\n",
    "            # Combine majority class with upsampled minority class\n",
    "            train_phq9 = pd.concat([train_majority, train_minority_upsampled])\n",
    "            \n",
    "            #seperate features and target\n",
    "            y_train = train_phq9[\"target\"] \n",
    "            X_train = train_phq9.drop(columns = \"target\") #remove target from training data\n",
    "            \n",
    "            \n",
    "            print(X_train.head())\n",
    "            print(X_test.head())\n",
    "            \n",
    "            for r in [1,2,4,8,16,32,64,128,256,512]: #random seeds for reproducibility\n",
    "                for modelType in modelTypelist:\n",
    "\n",
    "                    #add data to lists\n",
    "                    llist.append(label)\n",
    "                    featureList.append(f +1)\n",
    "                    flist.append(featureE)\n",
    "                    mlist.append(modelType)\n",
    "\n",
    "                    #chose model type\n",
    "                    #chose model type\n",
    "                    if modelType == \"SVC1\":\n",
    "                        clf = svm.SVC(kernel='rbf', random_state=r)\n",
    "                    elif modelType == \"SVC2\":\n",
    "                        clf = svm.SVC(kernel='linear', random_state=r)\n",
    "                    elif modelType == \"SVC3\":\n",
    "                        clf = svm.SVC(kernel='poly', random_state=r)\n",
    "                    elif modelType == \"SVC4\":\n",
    "                        clf = svm.SVC(kernel='sigmoid', random_state=r)\n",
    "                    elif modelType == \"RF2g\":\n",
    "                        clf = RandomForestClassifier(criterion=\"gini\", max_depth=2, random_state=r)\n",
    "                    elif modelType == \"RF2e\":\n",
    "                        clf = RandomForestClassifier(criterion=\"entropy\", max_depth=2, random_state=r)\n",
    "                    elif modelType == \"RF3g\":\n",
    "                        clf = RandomForestClassifier(criterion=\"gini\", max_depth=3, random_state=r)\n",
    "                    elif modelType == \"RF3e\":\n",
    "                        clf = RandomForestClassifier(criterion=\"entropy\", max_depth=3, random_state=r)\n",
    "                    elif modelType == \"RF4g\":\n",
    "                        clf = RandomForestClassifier(criterion=\"gini\", max_depth=4, random_state=r)\n",
    "                    elif modelType == \"RF4e\":\n",
    "                        clf = RandomForestClassifier(criterion=\"entropy\", max_depth=4, random_state=r)\n",
    "                    elif modelType == \"kNN1\":\n",
    "                        clf = KNeighborsClassifier(n_neighbors=1)\n",
    "                    elif modelType == \"kNN3\":\n",
    "                        clf = KNeighborsClassifier(n_neighbors=3)\n",
    "                    elif modelType == \"kNN5\":\n",
    "                        clf = KNeighborsClassifier(n_neighbors=5)\n",
    "                    elif modelType == \"kNN7\":\n",
    "                        clf = KNeighborsClassifier(n_neighbors=7)\n",
    "                    elif modelType == \"kNN9\":\n",
    "                        clf = KNeighborsClassifier(n_neighbors=9)\n",
    "                    elif modelType == \"XG2\":\n",
    "                        clf = xgb.XGBClassifier(max_depth=2, random_state=r)\n",
    "                    elif modelType == \"XG3\":\n",
    "                        clf = xgb.XGBClassifier(max_depth=3, random_state=r)\n",
    "                    elif modelType == \"XG4\":\n",
    "                        clf = xgb.XGBClassifier(max_depth=4, random_state=r)\n",
    "                    elif modelType == \"LR1\":\n",
    "                        clf = LogisticRegression(random_state=r)\n",
    "                    elif modelType == \"LR2\":\n",
    "                        clf = LogisticRegression(random_state=r, penalty = \"l2\")\n",
    "                    elif modelType == \"NB\":\n",
    "                        clf = GaussianNB()\n",
    "\n",
    "\n",
    "                    #train model and make predictions\n",
    "                    clf.fit(X_train, y_train)\n",
    "                    y_pred = clf.predict(X_test)\n",
    "\n",
    "                    #evaluate model\n",
    "                    conf_mat = confusion_matrix(list(testdata[label]), y_pred)\n",
    "                    TN = conf_mat[0][0]\n",
    "                    TP = conf_mat[1][1]\n",
    "                    FP = conf_mat[0][1]\n",
    "                    FN = conf_mat[1][0]\n",
    "                    precision = TP/(TP+FP)\n",
    "                    sensitivity = TP/(TP+FN)\n",
    "                    f1 = (2*precision*sensitivity)/(precision + sensitivity)\n",
    "                    accuracy = (TP+TN)/(TN+TP+FP+FN)\n",
    "\n",
    "                    #populate lists with results\n",
    "                    f1List.append(f1)\n",
    "                    accuracyList.append(accuracy)\n",
    "                    truePosList.append(TP)\n",
    "                    trueNegList.append(TN)\n",
    "                    falsePosList.append(FP)\n",
    "                    falseNegList.append(FN)\n",
    "                    predictions.append(y_pred)\n",
    "                    rseed.append(r)\n",
    "\n",
    "        #create dataframe to output results\n",
    "        resultsDF = pd.DataFrame()\n",
    "        resultsDF[\"label\"] = llist\n",
    "        resultsDF[\"Engineering\"] = flist\n",
    "        resultsDF[\"model\"] = mlist\n",
    "        resultsDF[\"nFeatures\"] = featureList\n",
    "        resultsDF[\"F1\"] = f1List\n",
    "        resultsDF[\"Accuracy\"] = accuracyList\n",
    "        resultsDF[\"truePos\"] = truePosList\n",
    "        resultsDF[\"trueNeg\"] = trueNegList\n",
    "        resultsDF[\"falsePos\"] = falsePosList\n",
    "        resultsDF[\"falseNeg\"] = falseNegList\n",
    "        resultsDF[\"predictions\"] = predictions\n",
    "        resultsDF[\"randomSeed\"] = rseed\n",
    "\n",
    "        resultsDF.to_csv(\"resultsAll85/Scripted\" + featureE + label + \".csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
